//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSv4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public string Stock_Number { get; set; }
        public string Item_Name { get; set; }
        public int Quantity { get; set; }
        public string Description { get; set; }
        public decimal Unit_Price { get; set; }
        public string Department { get; set; }
    }
}
